Nar module cleanups
haskell-nix/hnix-store pull request #41
Opened 2019-03-23 14:52 UTC by shlevy

2019-03-23 14:52 UTC, shlevy commented
Still a draft, will mark ready once the module is up to spec

2019-03-23 15:25 UTC, imalsogreg requested changes
Good reorg. Only nits to change.

2019-03-23 15:25 UTC, imalsogreg commented on hnix-store-core/src/System/Nix/Internal/Nar.hs
> +-- Directly taken from Eelco thesis
Do we know what this comment was referring to? The whole module, Nar effects? Probably not the Nar newtype.

2019-03-23 15:25 UTC, imalsogreg commented on hnix-store-core/src/System/Nix/Internal/Nar.hs
> +        -- putContents fSize bs = str "contents" <> int (BSL.length bs) <> (pad fSize bs)
Stale comment

2019-03-23 15:29 UTC, imalsogreg commented
(meta). Does `Draft` mean, hold off on commenting for now?

2019-03-23 15:34 UTC, shlevy commented
Draft means I'm still expecting more to come (in particular, so far I've only touched NarEffects and still need to go through the rest and add haddocks etc.), but still ready for comments on what's come so far.

Also, I'm trying to make to so every commit is in a workable state, so that if someone *wants* to depend on this before I'm done we can merge in and I can continue the rest later.

2023-11-25 19:51 UTC, sorki commented
The last commit [e5f1c7d](https://github.com/haskell-nix/hnix-store/pull/41/commits/e5f1c7d9bcf618c3d1351fb006699285402f42d5) was ported to `hnix-store-nar` in #259 (prompted via #252). 

The rest is kind-of obsolete maybe except for the `RawFilePath` patch but the new `filepath` would be a better fit, see also https://github.com/haskell-nix/hnix-store/issues/237

Closing

2023-11-25 19:51 UTC, closed without merging